[build]
  functions = "netlify/functions"     
  node_bundler = "esbuild"          

[functions]
  included_files = ["src/**"]          

[[redirects]]                        
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200
