[build]
  command = """
    set -e
    mkdir -p certs &&
    printf %s "$APPLE_PAY_CERT_B64" | base64 -d > certs/merchant_id.pem &&
    printf %s "$APPLE_PAY_KEY_B64"  | base64 -d > certs/merchant_id.key
  """
  functions = "netlify/functions"     
  node_bundler = "esbuild"

[functions]
  included_files = ["certs/*"]            

[[redirects]]                        
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200
